/*
 * ============LICENSE_START===================================================
 * Copyright (c) 2018 Amdocs
 * ============================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=====================================================
 */
package org.onap.pomba.contextbuilder.sdnc.rules;

import org.onap.pomba.contextbuilder.sdnc.model.ServiceEntity;

rule "ApiMapping-1"
    no-loop  true
    lock-on-active true
    when
      $s : ServiceEntity( serviceType not contains "vFW" )
    then
      $s.setApiName("GENERIC-RESOURCE-API");
end


rule "ApiMapping-2"
    no-loop  true
    lock-on-active true
    when
      $s : ServiceEntity( serviceType contains "vFW" )
    then
      $s.setApiName("VNF-API");
end
